"""LearningAgent — writes anti-pattern rules from failure events.

Routing:
- Failure on ai-software-house itself (target_repo=None): appends to roles/{agent_role}.md
- Failure on a target repo (target_repo set): appends to repo-patterns/{owner}-{repo}.md

This ensures each repo's lessons accumulate in the right place and are picked up
by _build_engineer_context() Tier B on the next task.
"""
import logging
from pathlib import Path

from agents.base_agent import BaseAgent
from agents.failure_record import FailureRecord

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).parent.parent

ANTIPATTERNS_HEADER = "\n\n## Anti-patterns\n\n<!-- LearningAgent appends dated entries below. Do not edit manually. -->\n"
REPO_PATTERNS_HEADER = "# Codebase Patterns for {repo}\n\n<!-- Auto-generated by LearningAgent. Add `.github/AGENTS.md` to the repo for human-maintained patterns. -->\n\n## Anti-patterns\n\n"


class LearningAgent(BaseAgent):
    """Analyses failures and appends anti-pattern rules to the appropriate patterns file."""

    role_name = "learning_agent"

    def run(self, failure: FailureRecord) -> None:
        """Process a failure event and write an anti-pattern rule.

        Routing:
        - failure.target_repo is None → write to roles/{agent_role}.md
        - failure.target_repo is set → write to repo-patterns/{slug}.md
        """
        today = failure.timestamp[:10]

        if failure.target_repo:
            self._write_to_repo_patterns(failure, today)
        else:
            self._write_to_role_file(failure, today)

    def _write_to_role_file(self, failure: FailureRecord, today: str) -> None:
        role_path = self._get_roles_dir() / f"{failure.agent_role}.md"

        if not role_path.exists():
            logger.warning(
                "LearningAgent: role file %s not found — cannot write anti-pattern",
                role_path,
            )
            return

        current_content = role_path.read_text(encoding="utf-8")
        anti_pattern = self._derive_antipattern(current_content, failure, today)
        self._append_to_file(role_path, current_content, anti_pattern)
        logger.info("LearningAgent: wrote anti-pattern to %s", role_path.name)

    def _write_to_repo_patterns(self, failure: FailureRecord, today: str) -> None:
        slug = failure.target_repo.replace("/", "-")
        patterns_path = self._get_repo_patterns_dir() / f"{slug}.md"

        if patterns_path.exists():
            current_content = patterns_path.read_text(encoding="utf-8")
        else:
            current_content = REPO_PATTERNS_HEADER.format(repo=failure.target_repo)
            patterns_path.write_text(current_content, encoding="utf-8")

        anti_pattern = self._derive_antipattern(current_content, failure, today)
        self._append_to_file(patterns_path, current_content, anti_pattern)
        logger.info("LearningAgent: wrote anti-pattern to repo-patterns/%s.md", slug)

    def _derive_antipattern(self, context: str, failure: FailureRecord, today: str) -> str:
        prompt = (
            f"Context file content:\n{context[:3000]}\n\n"
            f"Failure error:\n{failure.error}\n\n"
            f"Correct fix:\n{failure.fix}\n\n"
            f"Date: {today}\n\n"
            f"Write a single anti-pattern rule to prevent this exact failure."
        )
        result = self.call(prompt).strip()
        if result.startswith("- DO NOT"):
            return result
        if result.startswith("DO NOT"):
            return f"- {result}"
        return f"- DO NOT {result.lstrip('- ')}"

    def _append_to_file(self, path: Path, current_content: str, anti_pattern: str) -> None:
        if "## Anti-patterns" not in current_content:
            new_content = current_content.rstrip() + ANTIPATTERNS_HEADER + anti_pattern + "\n"
        else:
            new_content = current_content.rstrip() + "\n" + anti_pattern + "\n"
        path.write_text(new_content, encoding="utf-8")

    def _get_roles_dir(self) -> Path:
        return _REPO_ROOT / "roles"

    def _get_repo_patterns_dir(self) -> Path:
        return _REPO_ROOT / "repo-patterns"
